// CAR ACTION TYPES
export const ADD_CAR = "ADD_CAR";
export const DELETE_CAR = "DELETE_CAR";
export const UPDATE_CAR = "UPDATE_CAR";
export const FETCH_CARS = "FETCH_CARS";

//MANUFACTURER ACTION TYPES
export const FETCH_MANUFACTURERS = "FETCH_MANUFACTURERS";
export const CREATE_MANUFACTURER = "CREATE_MANUFACTURER";
